// Extended Machine — Arduino package for PseudoSystem
// Loaded via:  FROM LOCAL.PKG IMPORT arduino
//
// Browser mode  (window.APCSP_RUNTIME === 'browser' or unset):
//   Every robot command delegates to the existing robot globals so the
//   tilemap simulation works exactly as before.
//
// C++ mode  (window.APCSP_RUNTIME === 'cpp'):
//   Every robot command ALSO pushes an equivalent C++ line into
//   window.APCSP_CPP_OUTPUT[].  After running, call
//   window.APCSP_PACKAGES.arduino._getCpp() to get a complete .ino file
//   ready to flash to an Arduino with a motor driver + ultrasonic sensors.
//
// The package works by monkey-patching the four global robot helper
// functions that the interpreter's built-in keywords already call:
//   robotInit         ← SPAWN
//   robotMove         ← MOVE_FORWARD
//   robotCanMove      ← CAN_MOVE
//   robotRecordFrame  ← ROTATE_LEFT / ROTATE_RIGHT / RENDER / frame recording
// This means no changes to the interpreter pipeline are needed.

(function () {
  'use strict';

  window.APCSP_PACKAGES   = window.APCSP_PACKAGES   || {};
  window.APCSP_CPP_OUTPUT = window.APCSP_CPP_OUTPUT || [];

  // ── helpers ────────────────────────────────────────────────────────────────

  function isCpp() { return window.APCSP_RUNTIME === 'cpp'; }

  function emit(line) {
    (window.APCSP_CPP_OUTPUT = window.APCSP_CPP_OUTPUT || []).push(line);
  }

  // ── private state for rotation detection ───────────────────────────────────
  // We compare the robot's facing direction across consecutive frames to decide
  // whether a ROTATE_LEFT or ROTATE_RIGHT just happened.

  var _prevDir    = null;   // direction seen in previous robotRecordFrame call
  var _spawnFrame = false;  // true for exactly the one frame right after SPAWN

  // ── patch robotInit  (SPAWN) ───────────────────────────────────────────────
  var _origRobotInit = window.robotInit;
  window.robotInit = function (map, row, col) {
    _origRobotInit(map, row, col);              // run the simulation side
    if (isCpp())
      emit('// Robot spawned at row ' + (row + 1) + ' col ' + (col + 1));
    _spawnFrame = true;   // suppress rotation check for the frame that follows
  };

  // ── patch robotMove  (MOVE_FORWARD) ────────────────────────────────────────
  var _origRobotMove = window.robotMove;
  window.robotMove = function () {
    if (isCpp()) emit('motors.forward();');
    _origRobotMove();   // moves robot, updates robotRow/Col, calls robotRecordFrame
  };

  // ── patch robotCanMove  (CAN_MOVE) ─────────────────────────────────────────
  // Always returns the real simulation boolean so IF / REPEAT UNTIL logic
  // continues to work correctly in both modes.
  var _origRobotCanMove = window.robotCanMove;
  window.robotCanMove = function (dirStr) {
    var result = _origRobotCanMove(dirStr);
    if (isCpp()) {
      var d = (typeof dirStr === 'string') ? dirStr.toLowerCase() : 'forward';
      if      (d === 'left')  emit('ultrasonicLeft.read() < THRESHOLD');
      else if (d === 'right') emit('ultrasonicRight.read() < THRESHOLD');
      else                    emit('ultrasonic.read() < THRESHOLD');   // forward / backward
    }
    return result;
  };

  // ── patch robotRecordFrame  (ROTATE_LEFT / ROTATE_RIGHT / RENDER) ──────────
  // Called after every state change:
  //   • MOVE_FORWARD  — position changed, direction same   → no emit here (robotMove did it)
  //   • ROTATE_LEFT   — position same,  direction changed  → emit turnLeft
  //   • ROTATE_RIGHT  — position same,  direction changed  → emit turnRight
  //   • SPAWN (frame) — suppressed by _spawnFrame flag
  //   • RENDER        — row/col/dir are null               → emit map comment
  var _origRobotRecordFrame = window.robotRecordFrame;
  window.robotRecordFrame = function (map, row, col, dir) {
    if (isCpp()) {
      if (row === null) {
        // RENDER — just a map draw, no position
        emit('// Map loaded');
      } else if (!_spawnFrame && _prevDir !== null && dir !== _prevDir) {
        // Direction changed mid-run → ROTATE
        var delta = ((dir - _prevDir) + 4) % 4;
        emit(delta === 1 ? 'motors.turnRight();' : 'motors.turnLeft();');
      }
      // MOVE frames: direction is unchanged → nothing extra to emit
    }
    _spawnFrame = false;
    _prevDir    = (dir !== null) ? dir : _prevDir;  // keep _prevDir on pure RENDER calls
    _origRobotRecordFrame(map, row, col, dir);
  };

  // ── .ino boilerplate ───────────────────────────────────────────────────────
  // ── .ino boilerplate uses the firmware/ header files ─────────────────────────
  // Place motors.h and ultrasonic.h (from extended-machine/firmware/) in the
  // same folder as this generated sketch before compiling in the Arduino IDE.
  var BOILERPLATE_TOP = [
    '// Generated by PseudoSystem — paste motors.h + ultrasonic.h alongside this file.',
    '#include "motors.h"',
    '#include "ultrasonic.h"',
    '',
    'MotorController  motors;',
    '',
    'UltrasonicSensor ultrasonic(7, 8);        // front — CAN_MOVE("forward"/"backward")',
    'UltrasonicSensor ultrasonicLeft(11, 12);  // left  — CAN_MOVE("left")',
    'UltrasonicSensor ultrasonicRight(A0, A1); // right — CAN_MOVE("right")',
    '',
    '#define THRESHOLD 15  // cm — obstacle detection distance',
    '',
    'void setup() {',
    '    Serial.begin(9600);',
    '    motors.begin();',
    '    ultrasonic.begin();',
    '    ultrasonicLeft.begin();',
    '    ultrasonicRight.begin();',
    '}',
    '',
    'void loop() {',
  ].join('\n');

  var BOILERPLATE_BOT = '}';

  // ── public API ─────────────────────────────────────────────────────────────
  window.APCSP_PACKAGES.arduino = {

    // Called by index.md's run-button handler before every run so that
    // each execution starts with a clean C++ output buffer.
    _reset: function () {
      window.APCSP_CPP_OUTPUT = [];
      _prevDir    = null;
      _spawnFrame = false;
    },

    // Returns a complete, compilable .ino file built from the collected
    // C++ lines.  Call this after running in Flash mode to see / flash
    // the generated code.
    _getCpp: function () {
      var lines = window.APCSP_CPP_OUTPUT || [];
      var body  = lines.length
        ? lines.map(function (l) { return '    ' + l; }).join('\n')
        : '    // (nothing collected — run a program with Flash mode enabled)';
      return BOILERPLATE_TOP + '\n' + body + '\n' + BOILERPLATE_BOT;
    },
  };

})();
