# ─────────────────────────────────────────────────────────────────────────────
#  PseudoSystem VirtualBit — Cutebot micro:bit firmware
#
#  This is the hardware harness that makes the code generated by the browser-side
#  transpiler (em_microbit.js / "Export MicroPython" mode) run on a real Cutebot.
#
#  Workflow:
#    1. Write pseudocode in the browser using MOVE_FORWARD, ROTATE_LEFT, etc.
#    2. Open "Micro:bit 🔵" modal → switch to "Export MicroPython" mode → Run.
#    3. Click "View Generated MicroPython" to see the transpiled code.
#    4. Copy the transpiled code and paste it below the ── PASTE HERE ── marker,
#       replacing the demo block.
#    5. Flash all four files to your micro:bit using the micro:bit Python Editor
#       (python.microbit.org) or mu-editor:
#         motors.py   ← motor driver
#         sonar.py    ← ultrasonic sensor driver
#         firmware.py ← this file (rename to main.py on the device)
#
#  Default wiring (Cutebot built-in):
#    Left motor / Right motor  →  I2C address 0x10  (built-in, no wiring needed)
#    Front ultrasonic          →  P1 (Trig)  P2 (Echo)
#    Left / right sonar stubs  →  always return 999 cm (no side sensors on stock Cutebot)
#
#  Calibrate CELL_TIME_MS and TURN_TIME_MS in motors.py for your floor surface.
# ─────────────────────────────────────────────────────────────────────────────

from motors import motors
from sonar  import sonar, sonar_left, sonar_right

THRESHOLD = 15  # cm — obstacle detection distance (matches transpiler output)

# ── Paste your transpiled MicroPython here ─────────────────────────────────────
#
#  Replace the block below with the output from "View Generated MicroPython"
#  in the Micro:bit 🔵 modal.  The generated code runs once and stops.
#
#  Example output for:
#    SPAWN(map, 2, 2)
#    REPEAT UNTIL (NOT CAN_MOVE("forward")) {
#        MOVE_FORWARD()
#    }
#    ROTATE_LEFT()

# Robot spawned at row 2 col 2
while sonar.ping() < THRESHOLD:
    motors.forward()
motors.left()

# ── end of transpiled code ─────────────────────────────────────────────────────
