// ─────────────────────────────────────────────────────────────────────────────
//  PseudoSystem Extended Machine — Arduino firmware
//
//  This is the hardware harness that makes the robot commands generated by the
//  browser-side transpiler (em.js / "Flash to Arduino" mode) run on real iron.
//
//  Workflow:
//    1. Write pseudocode in the browser using MOVE_FORWARD, ROTATE_LEFT, etc.
//    2. Open "Arduino ⚡" modal → switch to "Flash to Arduino" mode → Run.
//    3. Click "View Generated C++" to see the transpiled loop() body.
//    4. Paste that body into the loop() below (replacing the demo), or use
//       the standalone .ino the modal generates (put motors.h + ultrasonic.h
//       in the same folder).
//    5. Upload with Arduino IDE.
//
//  Default wiring (edit pin constants in motors.h / ultrasonic.h):
//    Motor driver (L298N):  ENA=9  IN1=2  IN2=3  ENB=10  IN3=4  IN4=5
//    Front ultrasonic:      TRIG=7  ECHO=8
//    Left  ultrasonic:      TRIG=11 ECHO=12
//    Right ultrasonic:      TRIG=A0 ECHO=A1
// ─────────────────────────────────────────────────────────────────────────────

#include "motors.h"
#include "ultrasonic.h"

// ── Global hardware instances ─────────────────────────────────────────────────
MotorController  motors;

UltrasonicSensor ultrasonic(7, 8);          // front — used by CAN_MOVE("forward")
UltrasonicSensor ultrasonicLeft(11, 12);    // left  — used by CAN_MOVE("left")
UltrasonicSensor ultrasonicRight(A0, A1);   // right — used by CAN_MOVE("right")

// Obstacle threshold in centimetres (matches THRESHOLD in the transpiler output)
#define THRESHOLD 15

// ─────────────────────────────────────────────────────────────────────────────

void setup() {
  Serial.begin(9600);
  motors.begin();
  ultrasonic.begin();
  ultrasonicLeft.begin();
  ultrasonicRight.begin();
  Serial.println("PseudoSystem EM ready.");
}

// ── Paste your transpiled pseudocode here ────────────────────────────────────
//
//  Replace the body below with the output from "View Generated C++" in the
//  Arduino ⚡ modal.  The while(true) at the end halts after one run so the
//  program doesn't restart on the next loop() iteration.
//
//  Example output for:
//    SPAWN(map, 2, 2)
//    REPEAT UNTIL (NOT CAN_MOVE("forward")) {
//        MOVE_FORWARD()
//    }
//    ROTATE_LEFT()

void loop() {
  // ── your transpiled code goes here ──────────────────────────────────────────
  // Robot spawned at row 2 col 2
  while (ultrasonic.read() < THRESHOLD) {
    motors.forward();
  }
  motors.turnLeft();
  // ── end of transpiled code ───────────────────────────────────────────────────

  while (true);  // halt — prevents loop() from restarting the program
}
