// ─────────────────────────────────────────────────────────────────────────────
//  PseudoSystem Extended Machine — Arduino firmware
//
//  This is the hardware harness that makes the robot commands generated by the
//  browser-side transpiler (em.js / "Flash to Arduino" mode) run on real iron.
//
//  Workflow:
//    1. Write pseudocode in the browser using MOVE_FORWARD, ROTATE_LEFT, etc.
//    2. Open "Arduino ⚡" modal → switch to "Flash to Arduino" mode → Run.
//    3. Click "View Generated C++" to see the transpiled loop() body.
//    4. Paste that body into the loop() below (replacing the demo), or use
//       the standalone .ino the modal generates (put motors.h + ultrasonic.h
//       in the same folder).
//    5. Upload with Arduino IDE.
//
//  Default wiring (edit pin constants in motors.h / ultrasonic.h):
//    Motor driver (L298N):  ENA=9  IN1=2  IN2=3  ENB=10  IN3=4  IN4=5
//    Front ultrasonic:      TRIG=7  ECHO=8
//    Left  ultrasonic:      TRIG=11 ECHO=12
//    Right ultrasonic:      TRIG=A0 ECHO=A1
// ─────────────────────────────────────────────────────────────────────────────

#include "motors.h"
#include "ultrasonic.h"

// ── Global hardware instances ─────────────────────────────────────────────────
MotorController  motors;

UltrasonicSensor ultrasonic(7, 8);          // front — used by CAN_MOVE("forward")
UltrasonicSensor ultrasonicLeft(11, 12);    // left  — used by CAN_MOVE("left")
UltrasonicSensor ultrasonicRight(A0, A1);   // right — used by CAN_MOVE("right")

// Obstacle threshold in centimetres (matches THRESHOLD in the transpiler output)
#define THRESHOLD 15

// ─────────────────────────────────────────────────────────────────────────────

void setup() {
  Serial.begin(9600);
  motors.begin();
  ultrasonic.begin();
  ultrasonicLeft.begin();
  ultrasonicRight.begin();
  Serial.println("PseudoSystem EM ready.");
}

// ── Demo loop — replace with your transpiled pseudocode ──────────────────────
//
//  Example: the code below is what you'd get from the pseudocode:
//
//    SPAWN(map, 2, 2)
//    REPEAT UNTIL (NOT CAN_MOVE("forward")) {
//        MOVE_FORWARD()
//    }
//    ROTATE_LEFT()
//    REPEAT UNTIL (NOT CAN_MOVE("forward")) {
//        MOVE_FORWARD()
//    }

void loop() {
  // Navigate forward until wall, then turn left and repeat
  while (ultrasonic.read() < THRESHOLD) {
    // obstacle already in front — rotate to find clear path
    motors.turnLeft();
  }

  motors.forward();   // one step forward if clear

  // Small delay between iterations so we don't spin the sensor too fast
  delay(50);
}
